import { TextStyle, ViewStyle } from 'react-native';

export const defaultViewStyleAliases: Record<string, keyof ViewStyle> = {
  bg: 'backgroundColor',
  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  ps: 'paddingStart',
  pe: 'paddingEnd',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  ms: 'marginStart',
  me: 'marginEnd',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
  maxW: 'maxWidth',
  maxH: 'maxHeight',
  justify: 'justifyContent',
  items: 'alignItems',
  self: 'alignSelf',
  direction: 'flexDirection',
  wrap: 'flexWrap',
  basis: 'flexBasis',
  grow: 'flexGrow',
  shrink: 'flexShrink',
} as const;

export const defaultTextStyleAliases: Record<string, keyof TextStyle> = {
  size: 'fontSize',
  family: 'fontFamily',
  weight: 'fontWeight',
  spacing: 'letterSpacing',
  lh: 'lineHeight',
  ta: 'textAlign',
  tdl: 'textDecorationLine',
  tds: 'textDecorationStyle',
  tt: 'textTransform',
  wd: 'writingDirection',
  tav: 'textAlignVertical',
  ifp: 'includeFontPadding',
  tsc: 'textShadowColor',
  tso: 'textShadowOffset',
  tsr: 'textShadowRadius',
  tdc: 'textDecorationColor',
} as const;
