export const defaultAlias = {
  bg: 'backgroundColor',
  p: 'padding',
  pt: 'paddingTop',
  pr: 'paddingRight',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  ps: 'paddingStart',
  pe: 'paddingEnd',
  px: 'paddingHorizontal',
  py: 'paddingVertical',
  m: 'margin',
  mt: 'marginTop',
  mr: 'marginRight',
  mb: 'marginBottom',
  ml: 'marginLeft',
  ms: 'marginStart',
  me: 'marginEnd',
  mx: 'marginHorizontal',
  my: 'marginVertical',
  w: 'width',
  h: 'height',
  minW: 'minWidth',
  minH: 'minHeight',
  maxW: 'maxWidth',
  maxH: 'maxHeight',
  justify: 'justifyContent',
  items: 'alignItems',
  self: 'alignSelf',
  direction: 'flexDirection',
  wrap: 'flexWrap',
  basis: 'flexBasis',
  grow: 'flexGrow',
  shrink: 'flexShrink',
} as const;

//   size: 'fontSize',
//   weight: 'fontWeight',
//   align: 'textAlign',
